[package]
name = "sindra"
version = "0.1.0"
authors = ["Jamie Blondin <jblondin@gmail.com>"]

[workspace]

[dependencies]
regex = "0.2"
lazy_static = "0.2"
rustyline = { git = "https://github.com/kkawakam/rustyline" }
clap = "2.19.0"
sindra_plugin = { path = "sindra_plugin" }
